import { defineConfig } from 'oxlint';

export default defineConfig({
  plugins: ['typescript', 'import', 'jsdoc'],
  categories: {},
  rules: {
    'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
    'no-console': 'off',
    'no-alert': 'error',
    'no-param-reassign': 'error',
    'prefer-template': 'error',
    'no-bitwise': 'error',
    complexity: ['error', { max: 33 }],
    'no-unused-expressions': ['error', { allowShortCircuit: true }],
    'guard-for-in': 'error',
    'array-callback-return': ['error', { allowImplicit: true }],
    quotes: ['error', 'single', { avoidEscape: true }],
    'no-return-await': 'error',
    'max-lines': ['error', { max: 300, skipComments: true, skipBlankLines: true }],
    'import/namespace': 'off',
    'import/no-unresolved': 'off',
    'no-control-regex': 'off',
    'jsdoc/check-tag-names': 'off',
    'jsdoc/require-yields': 'off',
    'no-useless-rename': 'off',
    'no-constant-binary-expression': 'off',
    'no-unsafe-optional-chaining': 'off',
    'no-eval': 'off',
    'no-import-assign': 'off',
    'typescript/no-duplicate-type-constituents': 'off',
  },
  overrides: [
    {
      files: ['**/*.ts', '**/*.d.ts'],
      rules: {
        'typescript/ban-ts-comment': 'error',
        'typescript/consistent-type-imports': 'error',
        'typescript/no-unnecessary-type-assertion': 'error',
        'typescript/prefer-for-of': 'error',
        'typescript/no-floating-promises': ['error', { ignoreVoid: true }],
        'typescript/no-dynamic-delete': 'error',
        'typescript/no-unsafe-member-access': 'error',
        'typescript/unbound-method': 'error',
        'typescript/no-explicit-any': 'error',
        'typescript/no-empty-function': 'off',
        'typescript/prefer-optional-chain': ['error'],
        'typescript/no-redundant-type-constituents': 'off',
        'typescript/restrict-template-expressions': 'off',
        'typescript/await-thenable': 'warn',
        'typescript/no-base-to-string': 'off',
      },
    },
    {
      files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
      rules: {
        'typescript/ban-ts-comment': 'off',
        'typescript/consistent-type-imports': 'off',
        'typescript/prefer-optional-chain': 'off',
        'typescript/no-unnecessary-type-assertion': 'off',
        'typescript/prefer-for-of': 'off',
        'typescript/no-floating-promises': 'off',
        'typescript/no-dynamic-delete': 'off',
        'typescript/no-unsafe-member-access': 'off',
        'typescript/unbound-method': 'off',
        'typescript/no-explicit-any': 'off',
      },
    },
    {
      files: ['*.config.js', '*.config.mjs', '*.config.ts', 'vite.config.ts'],
      rules: {
        'no-console': 'off',
        'max-lines': 'off',
      },
    },
  ],
  env: {
    es2017: true,
    node: true,
  },
  globals: {},
  ignorePatterns: ['dist/**', 'node_modules/**'],
});
