import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { build } from 'esbuild';

interface BannerMapping {
  [inputFilePath: string]: {
    outputFilePath: string;
    banner: string;
  };
}

/**
 * Builds userscripts with banners using esbuild
 */
async function buildWithBanners(): Promise<void> {
  try {
    // Read the banner mapping generated by create-headers
    const distDir = './dist';
    const mapFilePath = join(distDir, 'banner-map.json');
    
    if (!readFileSync(mapFilePath, 'utf-8')) {
      console.error(`Banner mapping file not found: ${mapFilePath}`);
      console.error('Please run "pnpm run create-headers" first to generate the banner mapping.');
      process.exit(1);
    }
    
    const mapping: BannerMapping = JSON.parse(readFileSync(mapFilePath, 'utf-8'));
    
    if (Object.keys(mapping).length === 0) {
      console.warn('No banner mappings found. Nothing to build.');
      return;
    }
    
    console.log(`Building ${Object.keys(mapping).length} userscripts with banners...`);
    
    // Build each file with its specific banner
    for (const [inputFilePath, { outputFilePath, banner }] of Object.entries(mapping)) {
      try {
        await build({
          entryPoints: [inputFilePath],
          bundle: true,
          format: 'iife',
          charset: 'utf8',
          target: 'es2020',
          sourcemap: false, // We'll add banner after, so inline sourcemap might interfere
          banner: {
            js: banner
          },
          outfile: outputFilePath,
          logLevel: 'warning'
        });
        
        console.log(`✓ Built: ${outputFilePath}`);
      } catch (buildError) {
        console.error(`✗ Failed to build ${inputFilePath}: ${buildError}`);
      }
    }
    
    console.log('Build completed!');
  } catch (error) {
    console.error('Error in build process:', error);
    process.exit(1);
  }
}

// Execute the build
void buildWithBanners();