import type { MonkeyUserScript } from 'vite-plugin-monkey'
export function manifest(): MonkeyUserScript {
  return {
    name: 'Amazon - Add to Goodreads widget',
    namespace: 'https://github.com/bricemciver/GreasemonekeyScripts',
    description: 'Places an "Add to Goodreads" widget on Amazon book pages',
    license: 'MIT',
    version: '0.0.5',
    icon: 'https://www.google.com/s2/favicons?sz=64&domain=amazon.com',
    downloadURL: 'https://greasyfork.org/en/scripts/468321-amazon-add-to-goodreads-widget',
    match: [
      'https://openuserjs.org/scripts/*',
      'http://localhost:8080/scripts/*',
      'https://amazon.com/*',
      'https://*.amazon.com/*',
      'https://amazon.co.uk/*',
      'https://*.amazon.co.uk/*',
      'https://amazon.ca/*',
      'https://*.amazon.ca/*',
      'https://amazon.de/*',
      'https://*.amazon.de/*',
      'https://amazon.fr/*',
      'https://*.amazon.fr/*',
      'https://amazon.es/*',
      'https://*.amazon.es/*',
      'https://amazon.it/*',
      'https://*.amazon.it/*',
      'https://amazon.co.jp/*',
      'https://*.amazon.co.jp/*',
      'https://amazon.cn/*',
      'https://*.amazon.cn/*',
      'https://amazon.com.br/*',
      'https://*.amazon.com.br/*',
      'https://amazon.in/*',
      'https://*.amazon.in/*',
      'https://amazon.com.mx/*',
      'https://*.amazon.com.mx/*',
      'https://amazon.com.au/*',
      'https://*.amazon.com.au/*',
    ],
    grant: 'none',
  }
}
