---
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Format Source Code
        run: npm run format

      - name: Build
        run: npm run build

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          # https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
          message: 'chore: [skip-ci] format code and generate build artifacts'
