import type { MonkeyUserScript } from "vite-plugin-monkey";
export function manifest(): MonkeyUserScript {
  return {
    name: "Amazon - Hide Sponsored",
    namespace: "https://github.com/bricemciver/GreasemonekeyScripts",
    description: "Hide sponsored items from search results",
    license: "MIT",
    version: "0.0.1",
    supportURL: "https://github.com/bricemciver/GreasemonkeyScripts/issues",
    match: [
      "https://amazon.com/*",
      "https://*.amazon.com/*",
      "https://amazon.co.uk/*",
      "https://*.amazon.co.uk/*",
      "https://amazon.ca/*",
      "https://*.amazon.ca/*",
      "https://amazon.de/*",
      "https://*.amazon.de/*",
      "https://amazon.fr/*",
      "https://*.amazon.fr/*",
      "https://amazon.es/*",
      "https://*.amazon.es/*",
      "https://amazon.it/*",
      "https://*.amazon.it/*",
      "https://amazon.co.jp/*",
      "https://*.amazon.co.jp/*",
      "https://amazon.cn/*",
      "https://*.amazon.cn/*",
      "https://amazon.com.br/*",
      "https://*.amazon.com.br/*",
      "https://amazon.in/*",
      "https://*.amazon.in/*",
      "https://amazon.com.mx/*",
      "https://*.amazon.com.mx/*",
      "https://amazon.com.au/*",
      "https://*.amazon.com.au/*",
    ],
    icon: "https://www.google.com/s2/favicons?sz=64&domain=amazon.com",
  };
}
